"""Constants for the Bluesound HiFi wireless speakers and audio integrations component."""
DOMAIN = "bluesound_alt"
SERVICE_CLEAR_TIMER = "clear_sleep_timer"
SERVICE_JOIN = "join"
SERVICE_SET_TIMER = "set_sleep_timer"
SERVICE_UNJOIN = "unjoin"
